namalengkap = str(input('Enter name : '))
namap = str(input('Enter nickname  : '))
npm =int(input('Enter your NPM : '))
umur=int(input('Enter your age : '))
tempatlahir =str(input('Place of birth  : '))
alamat = str(input('Your address : '))
notelepon = int(input('Enter phone number : '))

print('Assalamualaikum,')
print('Let me introduce My self. My name is', namalengkap,'but you can call me',namap+'.')
print('My NPM is',npm,'I was born in',tempatlahir,'and i am',umur,'years old.')
print('I am very  glad if you want to invite my house in',alamat,'.So, dont forget to call me before with the number',notelepon,'.') 
print('Thank you.')